In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import glob


import pyarrow.dataset as ds
import pyarrow.parquet as pq

from sklearn.preprocessing import StandardScaler

In [3]:
#save everything into a big dataset


dataset = ds.dataset(r"janestreet\train.parquet", format="parquet", partitioning="hive")

table = dataset.to_table()
df = table.to_pandas()

# df.to_parquet("combined_train_raw.parquet", engine="pyarrow")

In [2]:
#prep single dataset
df = pd.read_parquet(r"janestreet\jane-street-real-time-market-data-forecasting\train.parquet\partition_id=9\part-0.parquet", engine="pyarrow")

# preprocessing

In [2]:
# df = pd.read_parquet(r"janestreet\combined_train_raw.parquet", engine='pyarrow')

In [3]:
df.describe()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,feature_78,responder_0,responder_1,responder_2,responder_3,responder_4,responder_5,responder_6,responder_7,responder_8
count,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,...,6.272631e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06
mean,1.614142e+03,4.835000e+02,1.901404e+01,2.361384e+00,1.873208e+00,2.602108e-02,1.864772e+00,1.864176e+00,-1.212088e-02,-4.847535e-02,...,1.325256e-02,-1.347268e-03,-8.555991e-04,3.291748e-04,-3.937317e-02,-3.898935e-02,-3.454752e-02,-3.780264e-03,-6.048032e-03,-2.954880e-04
std,4.882171e+01,2.794374e+02,1.124457e+01,1.094003e+00,1.452603e+00,1.133959e+00,1.444811e+00,1.445099e+00,9.951165e-01,9.423889e-01,...,9.748842e-01,4.137231e-01,4.167322e-01,4.244078e-01,1.007126e+00,9.346645e-01,9.650604e-01,8.097492e-01,8.244061e-01,7.907158e-01
min,1.530000e+03,0.000000e+00,0.000000e+00,5.324591e-01,-2.561013e+00,-4.274224e+00,-2.605949e+00,-2.540449e+00,-4.105798e+00,-1.239336e+01,...,-4.876283e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00
25%,1.572000e+03,2.417500e+02,9.000000e+00,1.523484e+00,7.104638e-01,-7.398547e-01,7.112520e-01,7.093264e-01,-6.788018e-01,-5.004615e-01,...,-2.731894e-01,-1.645727e-01,-1.354915e-01,-2.052442e-01,-3.006397e-01,-3.786564e-01,-2.284731e-01,-3.751850e-01,-4.153281e-01,-3.402549e-01
50%,1.614000e+03,4.835000e+02,1.900000e+01,2.162010e+00,2.011877e+00,-2.175932e-02,2.012542e+00,2.011695e+00,-1.520159e-02,-4.794242e-02,...,-1.445980e-01,-3.149339e-03,-2.037835e-02,2.297103e-05,-3.339716e-02,-5.760912e-02,-1.520078e-02,-3.443441e-02,-5.519713e-02,-1.534246e-02
75%,1.656000e+03,7.252500e+02,2.900000e+01,2.966673e+00,3.047259e+00,7.497100e-01,3.046757e+00,3.044584e+00,6.349058e-01,4.242871e-01,...,8.683352e-02,1.594334e-01,1.022870e-01,2.057978e-01,2.375821e-01,2.806393e-01,1.951360e-01,3.136375e-01,3.253073e-01,3.090042e-01
max,1.698000e+03,9.670000e+02,3.800000e+01,7.902302e+00,6.477002e+00,4.709325e+00,6.490265e+00,6.695623e+00,4.405029e+00,1.384570e+01,...,1.725921e+02,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00

In [4]:
df.head()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,feature_78,responder_0,responder_1,responder_2,responder_3,responder_4,responder_5,responder_6,responder_7,responder_8
0,1530,0,0,3.084694,1.153571,1.563784,0.697396,0.756759,2.580965,0.171311,...,0.999516,0.417462,0.323897,0.601499,2.074103,0.746552,0.552013,3.071231,0.914794,0.997124
1,1530,0,1,2.232906,0.553354,1.730064,0.990195,0.611490,2.023031,0.319015,...,0.160609,-0.318671,-0.399384,-0.635306,2.092151,0.342582,0.757289,1.979042,0.967537,1.219739
2,1530,0,2,2.404948,1.532503,2.095852,0.919688,0.583715,2.330047,0.337096,...,-0.065761,0.200878,-0.006571,0.518870,-0.344441,0.641694,-0.646040,-0.506260,0.739797,-2.041514
3,1530,0,3,1.986533,0.647099,1.687460,0.569406,1.061679,2.444131,0.150487,...,0.526284,-0.349773,-0.235901,-0.428956,-1.903627,-1.214619,-0.469500,-2.590589,-0.946317,-0.390001
4,1530,0,4,2.742601,1.096778,1.551411,0.632113,0.368218,2.181873,0.214604,...,-0.965623,-0.373938,-0.209282,-0.095182,-1.598217,0.968505,-0.705594,-1.579623,0.954296,-1.805623

In [5]:
#drop in place
l = ["date_id", "responder_0", "responder_1", "responder_2", "responder_3", "responder_4", "responder_5", "responder_7", "responder_8"]


df.drop(l, axis=1, inplace=True)

In [6]:
#drop in place for all useless(single value, binary or binary alike) features.

l_f = ["feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_21",
        "feature_31", "feature_47", "feature_62", "feature_63", "feature_64", "feature_68", "feature_71", "feature_72"]

df.drop(l_f, axis=1, inplace=True)

In [7]:
#drop all nan, drop all na rows
df.dropna(axis=0, inplace=True)

In [15]:
#reset index
df.reset_index(drop=True, inplace=True)

In [18]:
#saving
df.to_parquet("p10_train_prep_v2_nd_dropna_lf_row.parquet", engine="pyarrow")

In [16]:
df.head()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_67,feature_69,feature_70,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
0,68,0,3.084694,0.389057,2.749725,0.718424,1.256622,0.588988,0.247641,-2.901283,...,0.496783,0.729775,0.048784,0.008254,-0.084836,-0.198538,-0.317852,-0.160541,-0.281694,0.208288
1,68,1,2.232906,-0.026452,2.632656,0.187209,0.593603,0.481453,0.143793,-2.271466,...,0.410599,0.600609,0.306555,-0.038054,-0.104323,-0.227070,-0.227107,-0.095917,-0.119115,-0.550641
2,68,2,2.404948,1.013794,1.809883,-0.376363,0.559347,1.132689,0.188735,-2.102561,...,-0.204304,0.229562,0.201693,0.421981,0.506014,0.097484,0.061537,0.208154,0.424226,0.609057
3,68,3,1.986533,1.113055,2.298128,0.588921,0.045917,0.912620,0.213604,-2.596459,...,-0.079997,0.155563,0.202217,-0.488699,-0.281139,-0.914780,-0.920151,-1.141477,-0.942694,-0.663870
4,68,4,2.742601,0.429002,2.764029,0.838564,0.291231,0.691983,0.176078,-1.577382,...,-0.328838,0.009004,-0.157728,-0.293743,-0.398692,-0.361992,-0.482711,-0.302175,-0.290704,-0.251347

In [17]:
df.describe()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_67,feature_69,feature_70,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
count,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,...,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06,5.717539e+06
mean,5.170100e+02,1.880035e+01,2.373998e+00,1.879202e+00,-7.424746e-02,1.883134e+00,1.878812e+00,-7.541674e-02,-4.386092e-02,-6.741858e-03,...,-1.009803e-01,-1.357607e-01,-5.862090e-02,-2.671531e-02,-3.935972e-02,6.644737e-03,-4.300665e-03,-1.235496e-02,-2.376964e-02,-6.809300e-03
std,2.596301e+02,1.115288e+01,1.096360e+00,1.443793e+00,1.049745e+00,1.433977e+00,1.434426e+00,9.106299e-01,9.256310e-01,9.858216e-01,...,8.237185e-01,6.765475e-01,9.968948e-01,9.492068e-01,9.242020e-01,9.164542e-01,8.975788e-01,8.787290e-01,8.556059e-01,7.532809e-01
min,6.800000e+01,0.000000e+00,5.324591e-01,-2.403379e+00,-4.274224e+00,-2.583650e+00,-2.540449e+00,-3.952554e+00,-1.239336e+01,-3.153300e+01,...,-1.438817e+00,-1.107169e+00,-1.610412e+00,-5.403410e+00,-5.541708e+00,-4.585004e+00,-4.511707e+00,-4.800036e+00,-4.876283e+00,-5.000000e+00
25%,2.920000e+02,9.000000e+00,1.533418e+00,7.276371e-01,-7.779801e-01,7.367546e-01,7.329426e-01,-6.933730e-01,-4.856859e-01,-4.432500e-01,...,-4.788690e-01,-4.384558e-01,-4.549691e-01,-3.016572e-01,-3.166145e-01,-2.753119e-01,-2.897960e-01,-2.666100e-01,-2.798686e-01,-3.590904e-01
50%,5.170000e+02,1.900000e+01,2.179573e+00,2.013846e+00,-8.952833e-02,2.031662e+00,2.025253e+00,-5.389500e-02,-4.461993e-02,-2.623188e-03,...,-2.691573e-01,-2.871937e-01,-2.179762e-01,-1.804315e-01,-1.755792e-01,-1.920396e-01,-1.800292e-01,-1.603935e-01,-1.555412e-01,-3.408865e-02
75%,7.420000e+02,2.800000e+01,2.979284e+00,3.045245e+00,6.127785e-01,3.051596e+00,3.047584e+00,5.586372e-01,4.178105e-01,4.373264e-01,...,5.882559e-02,-4.327498e-02,1.262261e-01,4.258946e-02,4.427582e-02,7.284552e-02,6.959792e-02,5.521012e-02,5.669455e-02,2.969983e-01
max,9.670000e+02,3.800000e+01,7.902302e+00,6.477002e+00,4.402467e+00,6.490265e+00,6.695623e+00,3.631489e+00,1.384570e+01,3.391214e+01,...,9.384792e+01,1.102038e+02,1.676685e+02,2.437981e+01,2.671325e+01,3.912805e+01,4.342694e+01,2.693237e+01,2.776274e+01,5.000000e+00