In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import glob


import pyarrow.dataset as ds
import pyarrow.parquet as pq

from sklearn.preprocessing import StandardScaler

In [3]:
#save everything into a big dataset


dataset = ds.dataset(r"janestreet\jane-street-real-time-market-data-forecasting\train.parquet", format="parquet", partitioning="hive")

table = dataset.to_table()
df = table.to_pandas()

# df.to_parquet("combined_train_raw.parquet", engine="pyarrow")

In [2]:
#prep single dataset
df = pd.read_parquet(r"janestreet\jane-street-real-time-market-data-forecasting\train.parquet\partition_id=9\part-0.parquet", engine="pyarrow")

# preprocessing

In [2]:
# df = pd.read_parquet(r"janestreet\combined_train_raw.parquet", engine='pyarrow')

In [4]:
df.describe()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,responder_0,responder_1,responder_2,responder_3,responder_4,responder_5,responder_6,responder_7,responder_8,partition_id
count,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.712734e+07,...,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07
mean,1.005479e+03,4.687057e+02,1.810239e+01,2.009441e+00,5.738325e-01,1.019200e-02,5.731021e-01,5.727453e-01,-8.522313e-04,-3.837985e-02,...,-1.545146e-03,-8.655997e-04,-1.419603e-04,-1.638009e-02,-1.244198e-02,-1.662422e-02,-2.140646e-03,1.476110e-03,-1.113618e-03,5.409279e+00
std,4.451819e+02,2.725187e+02,1.130165e+01,1.152746e+00,1.284554e+00,1.024101e+00,1.279847e+00,1.279731e+00,9.742274e-01,9.580830e-01,...,5.547247e-01,5.580534e-01,5.607609e-01,7.744035e-01,8.215749e-01,6.986801e-01,8.418248e-01,8.617978e-01,8.175328e-01,2.610668e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,1.499667e-01,-5.794129e+00,-5.741592e+00,-5.726010e+00,-5.601890e+00,-5.799880e+00,-2.535040e+01,...,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,0.000000e+00
25%,6.790000e+02,2.330000e+02,9.000000e+00,1.210248e+00,-3.325972e-01,-7.210978e-01,-3.298276e-01,-3.304725e-01,-7.067508e-01,-4.875799e-01,...,-1.902501e-01,-1.637682e-01,-1.998778e-01,-3.100654e-01,-3.836545e-01,-2.254138e-01,-3.827613e-01,-4.197189e-01,-3.342880e-01,3.000000e+00
50%,1.060000e+03,4.670000e+02,1.700000e+01,1.749686e+00,4.057831e-01,7.341659e-03,4.070410e-01,4.063981e-01,2.275866e-03,-5.649172e-02,...,-4.543308e-03,-2.383126e-02,-8.624472e-04,-2.575430e-02,-4.468977e-02,-9.661748e-03,-2.556645e-02,-3.917187e-02,-8.617128e-03,6.000000e+00
75%,1.376000e+03,7.010000e+02,2.800000e+01,2.525645e+00,1.261608e+00,7.293766e-01,1.258622e+00,1.258682e+00,7.037091e-01,3.906223e-01,...,1.819475e-01,1.273834e-01,1.990622e-01,2.611124e-01,3.132633e-01,2.005779e-01,3.343208e-01,3.553231e-01,3.112021e-01,8.000000e+00
max,1.698000e+03,9.670000e+02,3.800000e+01,1.024042e+01,6.477002e+00,6.292391e+00,6.490265e+00,6.695623e+00,6.164160e+00,3.572622e+01,...,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,9.000000e+00

In [5]:
df.head()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,responder_0,responder_1,responder_2,responder_3,responder_4,responder_5,responder_6,responder_7,responder_8,partition_id
0,0,0,1,3.889038,NaN,NaN,NaN,NaN,NaN,0.851033,...,0.738489,-0.069556,1.380875,2.005353,0.186018,1.218368,0.775981,0.346999,0.095504,0
1,0,0,7,1.370613,NaN,NaN,NaN,NaN,NaN,0.676961,...,2.965889,1.190077,-0.523998,3.849921,2.626981,5.000000,0.703665,0.216683,0.778639,0
2,0,0,9,2.285698,NaN,NaN,NaN,NaN,NaN,1.056285,...,-0.864488,-0.280303,-0.326697,0.375781,1.271291,0.099793,2.109352,0.670881,0.772828,0
3,0,0,10,0.690606,NaN,NaN,NaN,NaN,NaN,1.139366,...,0.408499,0.223992,2.294888,1.097444,1.225872,1.225376,1.114137,0.775199,-1.379516,0
4,0,0,14,0.440570,NaN,NaN,NaN,NaN,NaN,0.955200,...,-0.373387,-0.502764,-0.348021,-3.928148,-1.591366,-5.000000,-3.572820,-1.089123,-5.000000,0

In [6]:
#drop in place
l = ["date_id", "responder_0", "responder_1", "responder_2", "responder_3", "responder_4", "responder_5", "responder_7", "responder_8"]


df.drop(l, axis=1, inplace=True)

In [7]:
#drop in place for all useless(single value, binary or binary alike) features.

l_f = ["feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_21",
        "feature_31", "feature_47", "feature_62", "feature_63", "feature_64", "feature_68", "feature_71", "feature_72"]

df.drop(l_f, axis=1, inplace=True)

In [8]:
#drop all nan, drop all na rows
df.dropna(axis=0, inplace=True)

In [15]:
#reset index
df.reset_index(drop=True, inplace=True)

In [9]:
#saving
df.to_parquet("combine_train_prep_v2_nd_dropna_lf_row.parquet", engine="pyarrow")

In [16]:
df.head()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_67,feature_69,feature_70,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
0,68,0,3.084694,0.389057,2.749725,0.718424,1.256622,0.588988,0.247641,-2.901283,...,0.496783,0.729775,0.048784,0.008254,-0.084836,-0.198538,-0.317852,-0.160541,-0.281694,0.208288
1,68,1,2.232906,-0.026452,2.632656,0.187209,0.593603,0.481453,0.143793,-2.271466,...,0.410599,0.600609,0.306555,-0.038054,-0.104323,-0.227070,-0.227107,-0.095917,-0.119115,-0.550641
2,68,2,2.404948,1.013794,1.809883,-0.376363,0.559347,1.132689,0.188735,-2.102561,...,-0.204304,0.229562,0.201693,0.421981,0.506014,0.097484,0.061537,0.208154,0.424226,0.609057
3,68,3,1.986533,1.113055,2.298128,0.588921,0.045917,0.912620,0.213604,-2.596459,...,-0.079997,0.155563,0.202217,-0.488699,-0.281139,-0.914780,-0.920151,-1.141477,-0.942694,-0.663870
4,68,4,2.742601,0.429002,2.764029,0.838564,0.291231,0.691983,0.176078,-1.577382,...,-0.328838,0.009004,-0.157728,-0.293743,-0.398692,-0.361992,-0.482711,-0.302175,-0.290704,-0.251347

In [10]:
df.describe()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_69,feature_70,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6,partition_id
count,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,...,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07,3.537144e+07
mean,5.127646e+02,1.873094e+01,2.053089e+00,5.769472e-01,-6.617299e-02,5.866070e-01,5.827268e-01,-5.335539e-02,-4.202563e-02,-7.270599e-03,...,-9.602757e-02,-2.155761e-02,-5.983765e-02,-6.791942e-02,-2.860866e-02,-3.568428e-02,-4.756387e-02,-5.488796e-02,-5.202522e-03,6.302992e+00
std,2.580611e+02,1.119400e+01,1.098935e+00,1.310954e+00,9.843734e-01,1.307165e+00,1.306492e+00,9.287552e-01,9.351200e-01,9.763896e-01,...,7.844532e-01,8.699627e-01,7.740217e-01,7.631896e-01,8.376875e-01,8.284172e-01,7.301707e-01,7.185910e-01,7.819499e-01,1.895040e+00
min,6.800000e+01,0.000000e+00,1.499667e-01,-4.220506e+00,-4.539880e+00,-4.368600e+00,-4.303587e+00,-4.363942e+00,-2.535040e+01,-5.860436e+01,...,-1.283782e+00,-1.894538e+00,-7.017025e+00,-6.107176e+00,-6.279804e+00,-5.730657e+00,-5.920879e+00,-6.159515e+00,-5.000000e+00,3.000000e+00
25%,2.880000e+02,9.000000e+00,1.242628e+00,-3.522897e-01,-7.638688e-01,-3.382683e-01,-3.428466e-01,-7.216767e-01,-4.701390e-01,-4.118872e-01,...,-4.594730e-01,-4.840477e-01,-3.426583e-01,-3.513026e-01,-2.911323e-01,-3.042364e-01,-2.972059e-01,-3.059866e-01,-3.618477e-01,5.000000e+00
50%,5.140000e+02,1.900000e+01,1.792350e+00,3.802449e-01,-4.683219e-02,3.915449e-01,3.875345e-01,-3.328180e-02,-5.802366e-02,-8.105770e-03,...,-2.920199e-01,-2.194345e-01,-2.256610e-01,-2.199379e-01,-2.257180e-01,-2.164625e-01,-2.047217e-01,-1.979841e-01,-2.737789e-02,6.000000e+00
75%,7.350000e+02,2.800000e+01,2.591199e+00,1.247006e+00,6.376709e-01,1.253276e+00,1.250002e+00,6.339947e-01,3.750652e-01,3.922864e-01,...,-1.372691e-02,1.753061e-01,3.454753e-02,3.389348e-02,-3.076292e-02,-2.853182e-02,2.333706e-02,2.351240e-02,3.089410e-01,8.000000e+00
max,9.670000e+02,3.800000e+01,1.024042e+01,6.477002e+00,6.140219e+00,6.490265e+00,6.695623e+00,4.107941e+00,2.806539e+01,9.364406e+01,...,1.102038e+02,1.676685e+02,5.131192e+01,5.091332e+01,1.695963e+02,1.615010e+02,7.025117e+01,6.995947e+01,5.000000e+00,9.000000e+00