In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import glob

from sklearn.preprocessing import StandardScaler

In [ ]:


# # Specify the directory containing your parquet files
# directory = "janestreet\jane-street-real-time-market-data-forecasting\train.parquet"

# # Use glob to find all .parquet files
# parquet_files = glob.glob("train.parquet/partition_id=*/part-*.parquet")

In [ ]:
# df = pd.read_parquet(r'janestreet\jane-street-real-time-market-data-forecasting\train.parquet\partition_id=6\part-0.parquet')

In [ ]:
#save everything into a big dataset

# import pyarrow.dataset as ds
# import pyarrow.parquet as pq

# dataset = ds.dataset(r"janestreet\jane-street-real-time-market-data-forecasting\train.parquet", format="parquet", partitioning="hive")

# table = dataset.to_table()
# df = table.to_pandas()

# df.to_parquet("combined_train_raw.parquet", engine="pyarrow")

# preprocessing

In [2]:
df = pd.read_parquet(r"janestreet\combined_train_raw.parquet", engine='pyarrow')

In [ ]:
# df.describe()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,responder_0,responder_1,responder_2,responder_3,responder_4,responder_5,responder_6,responder_7,responder_8,partition_id
count,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.394529e+07,4.712734e+07,...,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07,4.712734e+07
mean,1.005479e+03,4.687057e+02,1.810239e+01,2.009441e+00,5.738325e-01,1.019200e-02,5.731021e-01,5.727453e-01,-8.522313e-04,-3.837985e-02,...,-1.545146e-03,-8.655997e-04,-1.419603e-04,-1.638009e-02,-1.244198e-02,-1.662422e-02,-2.140646e-03,1.476110e-03,-1.113618e-03,5.409279e+00
std,4.451819e+02,2.725187e+02,1.130165e+01,1.152746e+00,1.284554e+00,1.024101e+00,1.279847e+00,1.279731e+00,9.742274e-01,9.580830e-01,...,5.547247e-01,5.580534e-01,5.607609e-01,7.744035e-01,8.215749e-01,6.986801e-01,8.418248e-01,8.617978e-01,8.175328e-01,2.610668e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,1.499667e-01,-5.794129e+00,-5.741592e+00,-5.726010e+00,-5.601890e+00,-5.799880e+00,-2.535040e+01,...,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,-5.000000e+00,0.000000e+00
25%,6.790000e+02,2.330000e+02,9.000000e+00,1.210248e+00,-3.325972e-01,-7.210978e-01,-3.298276e-01,-3.304725e-01,-7.067508e-01,-4.875799e-01,...,-1.902501e-01,-1.637682e-01,-1.998778e-01,-3.100654e-01,-3.836545e-01,-2.254138e-01,-3.827613e-01,-4.197189e-01,-3.342880e-01,3.000000e+00
50%,1.060000e+03,4.670000e+02,1.700000e+01,1.749686e+00,4.057831e-01,7.341659e-03,4.070410e-01,4.063981e-01,2.275866e-03,-5.649172e-02,...,-4.543308e-03,-2.383126e-02,-8.624472e-04,-2.575430e-02,-4.468977e-02,-9.661748e-03,-2.556645e-02,-3.917187e-02,-8.617128e-03,6.000000e+00
75%,1.376000e+03,7.010000e+02,2.800000e+01,2.525645e+00,1.261608e+00,7.293766e-01,1.258622e+00,1.258682e+00,7.037091e-01,3.906223e-01,...,1.819475e-01,1.273834e-01,1.990622e-01,2.611124e-01,3.132633e-01,2.005779e-01,3.343208e-01,3.553231e-01,3.112021e-01,8.000000e+00
max,1.698000e+03,9.670000e+02,3.800000e+01,1.024042e+01,6.477002e+00,6.292391e+00,6.490265e+00,6.695623e+00,6.164160e+00,3.572622e+01,...,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,9.000000e+00

In [12]:
df.head()

,date_id,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
0,0,0,1,3.889038,NaN,NaN,NaN,NaN,NaN,0.851033,...,-1.022690,0.152241,-0.659864,NaN,NaN,-0.261412,-0.211486,-0.335556,-0.281498,0.775981
1,0,0,7,1.370613,NaN,NaN,NaN,NaN,NaN,0.676961,...,-1.052685,-0.393726,-0.741603,NaN,NaN,-0.281207,-0.182894,-0.245565,-0.302441,0.703665
2,0,0,9,2.285698,NaN,NaN,NaN,NaN,NaN,1.056285,...,-0.863230,-0.241892,-0.709919,NaN,NaN,0.377131,0.300724,-0.106842,-0.096792,2.109352
3,0,0,10,0.690606,NaN,NaN,NaN,NaN,NaN,1.139366,...,-0.530602,4.765215,0.571554,NaN,NaN,-0.226891,-0.251412,-0.215522,-0.296244,1.114137
4,0,0,14,0.440570,NaN,NaN,NaN,NaN,NaN,0.955200,...,-1.141761,0.099631,-0.661928,NaN,NaN,3.678076,2.793581,2.618250,3.418133,-3.572820

In [5]:
#drop in place
l = ["responder_0", "responder_1", "responder_2", "responder_3", "responder_4", "responder_5", "responder_7", "responder_8", "partition_id"]

df.drop(l, axis=1, inplace=True)

In [13]:
df.drop("date_id", axis=1, inplace=True)

In [16]:
#saving
df.to_parquet("combined_train_prep_v1_nd.parquet", engine="pyarrow")

In [15]:
df.head()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
0,0,1,3.889038,NaN,NaN,NaN,NaN,NaN,0.851033,0.242971,...,-1.022690,0.152241,-0.659864,NaN,NaN,-0.261412,-0.211486,-0.335556,-0.281498,0.775981
1,0,7,1.370613,NaN,NaN,NaN,NaN,NaN,0.676961,0.151984,...,-1.052685,-0.393726,-0.741603,NaN,NaN,-0.281207,-0.182894,-0.245565,-0.302441,0.703665
2,0,9,2.285698,NaN,NaN,NaN,NaN,NaN,1.056285,0.187227,...,-0.863230,-0.241892,-0.709919,NaN,NaN,0.377131,0.300724,-0.106842,-0.096792,2.109352
3,0,10,0.690606,NaN,NaN,NaN,NaN,NaN,1.139366,0.273328,...,-0.530602,4.765215,0.571554,NaN,NaN,-0.226891,-0.251412,-0.215522,-0.296244,1.114137
4,0,14,0.440570,NaN,NaN,NaN,NaN,NaN,0.955200,0.262404,...,-1.141761,0.099631,-0.661928,NaN,NaN,3.678076,2.793581,2.618250,3.418133,-3.572820