In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import glob


import pyarrow.dataset as ds
import pyarrow.parquet as pq

from sklearn.preprocessing import StandardScaler

In [3]:
#save everything into a big dataset


dataset = ds.dataset(r"janestreet\train.parquet", format="parquet", partitioning="hive")

table = dataset.to_table()
df = table.to_pandas()

# df.to_parquet("combined_train_raw.parquet", engine="pyarrow")

In [2]:
#prep single dataset
df = pd.read_parquet(r"janestreet\train.parquet\partition_id=9\part-0.parquet", engine="pyarrow")

# preprocessing

In [2]:
df = pd.read_parquet(r"janestreet\combined_train_raw.parquet", engine='pyarrow')

In [9]:
df.describe()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
count,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,6.274576e+06,...,6.274576e+06,6.274576e+06,6.274576e+06,6.212869e+06,6.212869e+06,6.264096e+06,6.264096e+06,6.272631e+06,6.272631e+06,6.274576e+06
mean,4.835000e+02,1.901404e+01,2.361384e+00,1.873208e+00,2.602108e-02,1.864772e+00,1.864176e+00,-1.212088e-02,-4.847535e-02,-4.729467e-03,...,-6.790921e-02,-4.110396e-02,-7.042831e-02,1.004993e-02,-3.069994e-03,3.241393e-02,2.082079e-02,2.528398e-02,1.325256e-02,-3.780264e-03
std,2.794374e+02,1.124457e+01,1.094003e+00,1.452603e+00,1.133959e+00,1.444811e+00,1.445099e+00,9.951165e-01,9.423889e-01,1.037774e+00,...,1.028077e+00,7.068701e-01,9.252274e-01,1.057943e+00,1.032773e+00,9.682676e-01,9.487138e-01,1.000362e+00,9.748842e-01,8.097492e-01
min,0.000000e+00,0.000000e+00,5.324591e-01,-2.561013e+00,-4.274224e+00,-2.605949e+00,-2.540449e+00,-4.105798e+00,-1.239336e+01,-3.153300e+01,...,-1.826287e+00,-7.818221e-01,-1.293019e+00,-5.403410e+00,-5.541708e+00,-4.585004e+00,-4.511707e+00,-4.800036e+00,-4.876283e+00,-5.000000e+00
25%,2.417500e+02,9.000000e+00,1.523484e+00,7.104638e-01,-7.398547e-01,7.112520e-01,7.093264e-01,-6.788018e-01,-5.004615e-01,-4.619547e-01,...,-4.653203e-01,-3.176667e-01,-4.478851e-01,-2.961141e-01,-3.096867e-01,-2.722898e-01,-2.852278e-01,-2.613900e-01,-2.731894e-01,-3.751850e-01
50%,4.835000e+02,1.900000e+01,2.162010e+00,2.011877e+00,-2.175932e-02,2.012542e+00,2.011695e+00,-1.520159e-02,-4.794242e-02,-3.387760e-03,...,-2.250253e-01,-2.011355e-01,-2.467890e-01,-1.691768e-01,-1.647696e-01,-1.851486e-01,-1.736897e-01,-1.491035e-01,-1.445980e-01,-3.443441e-02
75%,7.252500e+02,2.900000e+01,2.966673e+00,3.047259e+00,7.497100e-01,3.046757e+00,3.044584e+00,6.349058e-01,4.242871e-01,4.548536e-01,...,1.205188e-01,2.099017e-02,8.076015e-02,7.066058e-02,7.110153e-02,1.022495e-01,9.635079e-02,8.792368e-02,8.683352e-02,3.136375e-01
max,9.670000e+02,3.800000e+01,7.902302e+00,6.477002e+00,4.709325e+00,6.490265e+00,6.695623e+00,4.405029e+00,1.384570e+01,3.391214e+01,...,1.676685e+02,1.865387e+02,2.084433e+02,1.356084e+02,1.218463e+02,1.191766e+02,1.148500e+02,2.081276e+02,1.725921e+02,5.000000e+00

In [8]:
df.head()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
0,0,0,3.084694,1.153571,1.563784,0.697396,0.756759,2.580965,0.171311,1.126353,...,-0.959100,1.284456,-0.275493,NaN,NaN,4.188457,3.666236,0.848177,0.999516,3.071231
1,0,1,2.232906,0.553354,1.730064,0.990195,0.611490,2.023031,0.319015,1.183371,...,-0.960126,0.306505,-0.522036,NaN,NaN,1.138142,1.579439,0.179564,0.160609,1.979042
2,0,2,2.404948,1.532503,2.095852,0.919688,0.583715,2.330047,0.337096,1.262236,...,-1.219395,0.359229,-0.636138,NaN,NaN,0.445388,0.300118,-0.043114,-0.065761,-0.506260
3,0,3,1.986533,0.647099,1.687460,0.569406,1.061679,2.444131,0.150487,0.896543,...,-1.398495,0.231285,-0.595247,NaN,NaN,6.995454,7.133929,0.352965,0.526284,-2.590589
4,0,4,2.742601,1.096778,1.551411,0.632113,0.368218,2.181873,0.214604,1.194230,...,-1.123492,0.120676,-0.610595,NaN,NaN,0.493589,0.560821,-1.332615,-0.965623,-1.579623

In [6]:
#drop in place
l = ["date_id", "responder_0", "responder_1", "responder_2", "responder_3", "responder_4", "responder_5", "responder_7", "responder_8"]

df.drop(l, axis=1, inplace=True)

In [10]:
#drop all nan, drop all na rows
df.dropna(axis=0, inplace=True)

In [13]:
#saving
df.to_parquet("p10_train_prep_v1_nd_dropna_row.parquet", engine="pyarrow")

In [11]:
df.head()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
2516,68,0,3.084694,0.389057,2.749725,0.718424,1.256622,0.588988,0.247641,-2.901283,...,0.048784,0.021539,0.107746,0.008254,-0.084836,-0.198538,-0.317852,-0.160541,-0.281694,0.208288
2517,68,1,2.232906,-0.026452,2.632656,0.187209,0.593603,0.481453,0.143793,-2.271466,...,0.306555,0.446082,0.718951,-0.038054,-0.104323,-0.227070,-0.227107,-0.095917,-0.119115,-0.550641
2518,68,2,2.404948,1.013794,1.809883,-0.376363,0.559347,1.132689,0.188735,-2.102561,...,0.201693,-0.081403,0.505405,0.421981,0.506014,0.097484,0.061537,0.208154,0.424226,0.609057
2519,68,3,1.986533,1.113055,2.298128,0.588921,0.045917,0.912620,0.213604,-2.596459,...,0.202217,-0.194793,0.103417,-0.488699,-0.281139,-0.914780,-0.920151,-1.141477,-0.942694,-0.663870
2520,68,4,2.742601,0.429002,2.764029,0.838564,0.291231,0.691983,0.176078,-1.577382,...,-0.157728,0.459309,0.067714,-0.293743,-0.398692,-0.361992,-0.482711,-0.302175,-0.290704,-0.251347

In [12]:
df.describe()

,time_id,symbol_id,weight,feature_00,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,...,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,responder_6
count,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,...,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06,5.717524e+06
mean,5.170112e+02,1.880038e+01,2.373997e+00,1.879201e+00,-7.425108e-02,1.883134e+00,1.878811e+00,-7.541627e-02,-4.386147e-02,-6.740444e-03,...,-5.862134e-02,-8.529356e-02,-1.249890e-01,-2.671904e-02,-3.936333e-02,6.640913e-03,-4.304556e-03,-1.235832e-02,-2.377303e-02,-6.807487e-03
std,2.596294e+02,1.115287e+01,1.096362e+00,1.443794e+00,1.049744e+00,1.433979e+00,1.434428e+00,9.106308e-01,9.256322e-01,9.858216e-01,...,9.968961e-01,5.899644e-01,7.950305e-01,9.492053e-01,9.242007e-01,9.164518e-01,8.975763e-01,8.787281e-01,8.556041e-01,7.532803e-01
min,6.800000e+01,0.000000e+00,5.324591e-01,-2.403379e+00,-4.274224e+00,-2.583650e+00,-2.540449e+00,-3.952554e+00,-1.239336e+01,-3.153300e+01,...,-1.610412e+00,-7.818221e-01,-1.293019e+00,-5.403410e+00,-5.541708e+00,-4.585004e+00,-4.511707e+00,-4.800036e+00,-4.876283e+00,-5.000000e+00
25%,2.920000e+02,9.000000e+00,1.533418e+00,7.276349e-01,-7.779822e-01,7.367523e-01,7.329405e-01,-6.933728e-01,-4.856873e-01,-4.432464e-01,...,-4.549696e-01,-3.242406e-01,-4.608145e-01,-3.016576e-01,-3.166149e-01,-2.753123e-01,-2.897968e-01,-2.666102e-01,-2.798689e-01,-3.590873e-01
50%,5.170000e+02,1.900000e+01,2.179573e+00,2.013844e+00,-8.953134e-02,2.031657e+00,2.025253e+00,-5.389354e-02,-4.462123e-02,-2.622147e-03,...,-2.179771e-01,-2.162611e-01,-2.742269e-01,-1.804323e-01,-1.755799e-01,-1.920399e-01,-1.800302e-01,-1.603940e-01,-1.555421e-01,-3.408783e-02
75%,7.420000e+02,2.800000e+01,2.979284e+00,3.045248e+00,6.127727e-01,3.051597e+00,3.047585e+00,5.586407e-01,4.178104e-01,4.373267e-01,...,1.262264e-01,-2.499866e-02,1.443993e-02,4.258706e-02,4.427239e-02,7.284203e-02,6.959377e-02,5.520553e-02,5.669179e-02,2.969996e-01
max,9.670000e+02,3.800000e+01,7.902302e+00,6.477002e+00,4.402467e+00,6.490265e+00,6.695623e+00,3.631489e+00,1.384570e+01,3.391214e+01,...,1.676685e+02,1.556564e+02,1.525039e+02,2.437981e+01,2.671325e+01,3.912805e+01,4.342694e+01,2.693237e+01,2.776274e+01,5.000000e+00