In [1]:
import yfinance as yf
import pandas as pd
from df_preprocessing import convert_to_pct
import os

import time

In [2]:
target = 'GOOG'
target_ticker = yf.Ticker(target)
target_df = target_ticker.history(start='2010-01-01', end='2020-12-31', interval='1d')

In [3]:
#processing 


target_df = target_df.reset_index()

In [4]:
drop_list = ['Dividends', 'Stock Splits']
target_df.drop(drop_list, axis=1, inplace=True)
target_df = target_df.rename(columns= lambda x :  x.lower() )

#trim down to 1d inerval time
target_dt = pd.to_datetime(target_df['date'])
target_df['date'] = target_dt.dt.strftime('%Y-%m-%d')

#trim volumn

In [5]:
#volumn trim
target_df = target_df[target_df['volume'] != 0]

In [6]:
#add pct
pct_df = target_df.copy()
convert_to_pct(pct_df, ['open', 'high', 'low', 'close'], drop_NA=True)
pct_df = pct_df.reset_index().drop('index', axis=1)

In [7]:
#saving
target_df.to_csv('google_index_spec_s.csv', index=False)

#save pct
pct_df.to_csv('google_index_pct_spec_s.csv', index=False)

In [8]:
target_df

            date       open       high        low      close     volume
0     2010-01-04  15.615220  15.678981  15.547723  15.610239   78541293
1     2010-01-05  15.620949  15.637387  15.480475  15.541497  120638494
2     2010-01-06  15.588072  15.588072  15.102393  15.149715  159744526
3     2010-01-07  15.178109  15.193053  14.760922  14.797037  257533695
4     2010-01-08  14.744733  15.024933  14.672753  14.994298  189680313
...          ...        ...        ...        ...        ...        ...
2763  2020-12-23  86.405502  87.399498  86.251999  86.619003   20676000
2764  2020-12-24  86.750000  87.300003  86.455498  86.942497    6936000
2765  2020-12-28  87.581749  89.536400  87.316750  88.804497   27860000
2766  2020-12-29  89.389503  89.622002  87.804497  87.935997   25988000
2767  2020-12-30  88.100502  88.254753  86.279999  86.975998   26122000

[2768 rows x 6 columns]

In [9]:
pct_df

,date,open,high,low,close,volume,open_pct_change,high_pct_change,low_pct_change,close_pct_change
0,2010-01-05,15.620949,15.637387,15.480475,15.541497,120638494,0.036687,-0.265282,-0.432522,-0.440364
1,2010-01-06,15.588072,15.588072,15.102393,15.149715,159744526,-0.210467,-0.315369,-2.442317,-2.520876
2,2010-01-07,15.178109,15.193053,14.760922,14.797037,257533695,-2.629977,-2.534108,-2.261037,-2.327953
3,2010-01-08,14.744733,15.024933,14.672753,14.994298,189680313,-2.855272,-1.106561,-0.597314,1.333111
4,2010-01-11,15.055070,15.055070,14.795543,14.971633,289597429,2.104732,0.200580,0.836853,-0.151158
...,...,...,...,...,...,...,...,...,...,...
2762,2020-12-23,86.405502,87.399498,86.251999,86.619003,20676000,-0.364378,0.609243,0.727846,0.515231
2763,2020-12-24,86.750000,87.300003,86.455498,86.942497,6936000,0.398699,-0.113839,0.235935,0.373468
2764,2020-12-28,87.581749,89.536400,87.316750,88.804497,27860000,0.958788,2.561737,0.996179,2.141645
2765,2020-12-29,89.389503,89.622002,87.804497,87.935997,25988000,2.064077,0.095606,0.558595,-0.977991
2766,2020-12-30,88.100502,88.254753,86.279999,86.975998,26122000,-1.442005,-1.525572,-1.736241,-1.091702